### ISSUE TITLE
Problema nell'esecuzione del file .bat quando sono presenti spazi all'interno del PATH

### ISSUE THREAD

**Issue by LorenzoBruno** [asmeta/asmeta#51]
Nel caso in cui all'interno del PATH sia presente una o più cartelle contenenti degli spazi vuoti (es. C:\Users\Lorenzo Bruno), l'esecuzione del .bat solleva errore segnalando di non essere stato in grado di trovare il percorso (es. "C:\Users\Lorenzo" non trovato). 

Una soluzione sarebbe quella di chiudere il percorso tra "" (in questo modo: "%CD%\eclipse\eclipse") facendo si che vengano ignorati tutti gli spazi vuoti. Aggiungendo delle doppie virgolette, però, l'interpretazione del comando cambia in quanto viene ricercato il file "-clean". Per questo motivo bisognerebbe aggiungere uno "" aggiuntivo prima del path.

La soluzione dovrebbe essere la seguente:

`START /b "" "%CD%\eclipse\eclipse" -clean`

(Non sono stati effettuati approfonditi test)

**Comment by garganti** [comment]
Grazie, sembra andare anche leggendo qualche info su Internet.  Modificato, dalla prossima release uso questo.
