### ISSUE TITLE
Difficulties running Asm2C++.

### ISSUE THREAD

**Issue by schwerdf** [asmeta/asmeta#59]
I recently tried to run the Asm2C++ tool as compiled from source (revision 38b884ee) in a development environment.

I got the plugin to start and the "Generate Arduino code!" button to appear. I then created a project containing the sample tic-tac-toe state machine, opened the file, and clicked the "Generate Arduino code!" button. Here I ran into the following difficulties:

* On Linux (several different distributions), the plugin hangs the Eclipse installation at [this line](https://github.com/asmeta/asmeta/blob/master/code/experimental/asmetal2cpp/asmetal2cpp_plugin/src/asm2code_inoproject/handlers/GeneratorHandler.java#L157).
* On Windows, the dialog box shows, but it looks like a required JAR for the GSON plugin is missing from the repository -- the translation process fails with a `NoClassDefFoundError` on the class `com.google.gson.GsonBuilder`:
```
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
	at org.asmeta.codegenerator.JsonGenerator.compile(JsonGenerator.java:475)
	at org.asmeta.codegenerator.JsonGenerator.generate(JsonGenerator.java:116)
	at asm2code_inoproject.handlers.GeneratorHandler.execute(GeneratorHandler.java:76)
...
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder cannot be found by asmeta.asmetal2cpp.hw_22.4.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
...
```

**Comment by garganti** [comment]
Sorry the GUI of the  Asm2C++  tool is not very well supported ... I'll take a look at it.

**Comment by podhrmic** [comment]
@garganti is there a command line option to run the C++ code generation? We would be happy to run it without the GUI, and for added context - we are more interested in the generated C++ code than the Arduino specific part (pin mappings etc), since we will not be running the code on arduino (in case that makes the debugging easier for you)?

**Comment by podhrmic** [comment]
We have the CLI version of the plugin running. @schwerdf can you close this issue?

**Comment by schwerdf** [comment]
As far as I know the plugin version is still hanging in Linux, but we sorted out the missing GSON dependencies in our fork and we have the CLI version running, so this can be closed.
