### ISSUE TITLE
Cannot build ASMeta?

### ISSUE THREAD

**Issue by podhrmic** [asmeta/asmeta#60]
Hello!
When attempting to build ASMeta and following the commands in [.gitlab-ci.yml](https://github.com/asmeta/asmeta/blob/master/.gitlab-ci.yml) I get the following errors:

```
$ docker run -v $PWD:/work -w /work -it maven:3.9.3-eclipse-temurin-20-alpine mvn compile -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true  -Djava.awt.headless=true
...
[INFO] Reactor Summary for asmeta.all 0.0.1-SNAPSHOT:
[INFO] 
[INFO] asmeta.emf ......................................... SUCCESS [  9.946 s]
[INFO] asmeta.parser ...................................... SUCCESS [  4.619 s]
[INFO] asmeta.cli ......................................... SUCCESS [  0.257 s]
[INFO] asmeta.parser.cli .................................. SUCCESS [  0.118 s]
[INFO] asmeta.parser.test ................................. SUCCESS [  0.006 s]
[INFO] asmeta.simulator ................................... SUCCESS [  0.395 s]
[INFO] asmeta.all ......................................... SUCCESS [  6.868 s]
[INFO] asmeta.simulator.cli ............................... SUCCESS [  0.027 s]
[INFO] asmeta.simulator.test .............................. SUCCESS [  0.151 s]
[INFO] asmeta.core ........................................ SUCCESS [  0.002 s]
[INFO] asmeta.flattener ................................... SUCCESS [  0.216 s]
[INFO] asmeta.smv ......................................... SUCCESS [  0.185 s]
[INFO] asmeta.flattener.test .............................. SUCCESS [  0.005 s]
[INFO] asmeta.smv.test .................................... SUCCESS [  0.005 s]
[INFO] report.aggregate ................................... SUCCESS [  0.006 s]
[INFO] asmeta.flattener.cli ............................... SUCCESS [  0.028 s]
[INFO] asmeta.modeladvisor ................................ SUCCESS [  0.114 s]
[INFO] asmeta.modeladvisor.test ........................... SUCCESS [  0.007 s]
[INFO] asmeta.traslatortosmt .............................. SUCCESS [  0.423 s]
[INFO] asmeta.refprover ................................... SUCCESS [  0.078 s]
[INFO] asmeta.validator ................................... FAILURE [  4.626 s]
[INFO] asmeta.visualizer .................................. SKIPPED
[INFO] asmetal2cpp_codegen ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.196 s
[INFO] Finished at: 2023-07-26T19:39:08Z
[INFO] ------------------------------------------------------------------------
...
```

Note that using different versions of `maven` docker image, and only running `mvn compile`without the extra arguments yields the same results.

Can you please advise on how to build ASMeta?

**Comment by schwerdf** [comment]
The errors that cause the build failure seem to be the result of some Xtext-generated source files (in the `org.asmeta.avallaxt/src-gen` directory) not being in the classpath when the `asmeta.validator` project is compiled.

**Comment by garganti** [comment]
We actually build asmeta inside eclipse, and not all the projects are maven projects (like `org.asmeta.avallaxt`). Inside eclipse every project compiles fine to me. In the future, we should move eventually every project to maven.
Now I converted the project `org.asmeta.avallaxt` to maven and should work now:
        [INFO] [1mReactor Summary for asmeta.all 0.0.1-SNAPSHOT:[m
        [INFO] 
        [INFO] asmeta.emf ......................................... [1;32mSUCCESS[m [  1.260 s]
        [INFO] asmeta.parser ...................................... [1;32mSUCCESS[m [  0.233 s]
        [INFO] asmeta.cli ......................................... [1;32mSUCCESS[m [  0.037 s]
        [INFO] asmeta.parser.cli .................................. [1;32mSUCCESS[m [  1.098 s]
        [INFO] asmeta.parser.test ................................. [1;32mSUCCESS[m [  0.111 s]
        [INFO] asmeta.simulator ................................... [1;32mSUCCESS[m [  0.085 s]
        [INFO] asmeta.all ......................................... [1;32mSUCCESS[m [  0.169 s]
        [INFO] asmeta.simulator.cli ............................... [1;32mSUCCESS[m [  0.883 s]
        [INFO] asmeta.simulator.test .............................. [1;32mSUCCESS[m [  0.038 s]
        [INFO] asmeta.core ........................................ [1;32mSUCCESS[m [  0.017 s]
        [INFO] asmeta.flattener ................................... [1;32mSUCCESS[m [  0.063 s]
        [INFO] asmeta.smv ......................................... [1;32mSUCCESS[m [  0.797 s]
        [INFO] asmeta.flattener.test .............................. [1;32mSUCCESS[m [  0.031 s]
        [INFO] asmeta.smv.test .................................... [1;32mSUCCESS[m [  0.037 s]
        [INFO] report.aggregate ................................... [1;32mSUCCESS[m [  1.456 s]
        [INFO] asmeta.flattener.cli ............................... [1;32mSUCCESS[m [  0.798 s]
        [INFO] asmeta.modeladvisor ................................ [1;32mSUCCESS[m [  2.130 s]
        [INFO] asmeta.modeladvisor.test ........................... [1;32mSUCCESS[m [  0.035 s]
        [INFO] asmeta.traslatortosmt .............................. [1;32mSUCCESS[m [  0.976 s]
        [INFO] asmeta.refprover ................................... [1;32mSUCCESS[m [  1.540 s]
        [INFO] org.asmeta.avallaxt ................................ [1;32mSUCCESS[m [  0.305 s]
        [INFO] asmeta.validator ................................... [1;32mSUCCESS[m [  2.501 s]
        [INFO] asmeta.visualizer .................................. [1;32mSUCCESS[m [  0.159 s]
        [INFO] asmetal2cpp_codegen ................................ [1;32mSUCCESS[m [  1.624 s]
        [INFO] [1m------------------------------------------------------------------------[m
        [INFO] [1;32mBUILD SUCCESS`

Please check

**Comment by podhrmic** [comment]
@garganti thanks for your quick response! Building on top of your recent changes, we were able to build ASMeta using maven, and run it as a part of github's CI - please see the associated pull request https://github.com/asmeta/asmeta/pull/62 

Is this an enhancement you would be willing to accept? For our use case, being able to build ASMeta from a command line, and having this build a part of the CI is important.

**Comment by garganti** [comment]
now the build under github should work.  We cannot accept #62  ... see there the explanation why

**Comment by garganti** [comment]
now asmeta builds correclty with maven (skipping the tests)
