### ISSUE TITLE
Model Advisor CLI exit codes

### ISSUE THREAD

**Issue by podhrmic** [asmeta/asmeta#79]
For CI/CD and automated testing, it would be useful if the model advisor CLI returned different exit codes based on the MA findings.

For example, if no advisory is needed, the returned value is 0 (no error):
```
bash-4.2# java -jar /opt/asm-dist/AsmetaMA.jar -mp1 example.asm
updateMap [dummy, state]
MP1: No inconsistent update is ever performed
NONE
bash-4.2# echo $?
0
```

but if model advisory was generated, the return value is non-zero so it can be processed in a script:
```
bash-4.2# java -jar /opt/asm-dist/AsmetaMA.jar -mp6 example.asm
MP6: Every controlled location can take any value in its codomain
Function dummy should be removed, because it's never used.

bash-4.2# echo $?
1
```

Is it possible to enable different exit codes?

**Comment by podhrmic** [comment]
I think a similar feature would be useful for the Model Validator as well, in case `some checks failed` message is printed, the exit code will be 1.

**Comment by garganti** [comment]
I can add an option to every AsmetaCLI subclass something like `--exitcode` and in that case the main will call `System.exit` if something goes wrong (whatever it means ... this is a little bit unclear at this point).

**Comment by garganti** [comment]
I've modified the code. Now every CLI version uses (if requested) the exit code to signal problems. The semantics should be:
- 0 if everything went well (SUCCESS)
- 1 if some FATAL error occurred (no analysis could be performed)
- 2 if some WARNING or some violation has been found 

For example:
```
> java -jar AsmetaMA.jar -mp2 -exit  caseIsComplete.asm
parsing file caseIsComplete.asm
file successfully parsed for asm caseIsComplete
MP2: Every conditional rule must be complete
ConditionalRule if (mon2) is not complete.
....
> $LASTEXITCODE
2
> java -jar AsmetaMA.jar -mp1 -exit caseIsComplete.asm
parsing file caseIsComplete.asm
file successfully parsed for asm caseIsComplete
updateMap [fooA, fooB, fooC, fooD, fooE, fooF, fooG_1, fooG_2, fooG_3, fooG_4]
MP1: No inconsistent update is ever performed
NONE
> $LASTEXITCODE
0
> java -jar AsmetaMA.jar -mp1 -exit wrongfile.txt
> $LASTEXITCODE
1
```

**Comment by podhrmic** [comment]
Excellent, thanks for the update!

**Comment by podhrmic** [comment]
@garganti any chance you can enable this behavior by default? It would be useful for catching various errors, for example not having NuSMV properly installed, not having a valid file etc. For example:
```
root@f15c89ee2893:/work# java -jar /opt/asmeta/asmeta-dist/AsmetaSMV.jar -en somefile
Error:  file somefile does not exist!
java -jar AsmetaSMV.jar [options...] file.asm
 -dcx           : disable computation of counterexamples (default: false)
 -debug         : set log4j level to debug (default: false)
 -en            : execute the NuSMV model after the translation (default: true)
 -exit          : use system.exit at the end (default: false)
 -kf            : keep the NuSMV file. To be used with the -en option enabled.
                  If the -en option is not enabled, the option -kf is enabled
                  by default. (default: false)
 -log VAL       : log4j configuration file
 -nc            : do not add the check on integer enum (default: false)
 -ns            : do not simplify the boolean conditions in NuSMV code
                  (default: false)
 -nusmvpath VAL : nusmv path

  Example: java -jar AsmetaSMV.jar -dcx -debug -en -exit -kf -log VAL -nc -ns -nusmvpath VAL file.asm
root@f15c89ee2893:/work# echo $?
0
```

In the CI, the default behavior is to have nonzero exit code upon exit. I am not sure what is the use case for always returning 0?

**Comment by podhrmic** [comment]
I see that in some cases the CLI returns non-zero exit code, even though there is no error:
```
root@7da45b53d672:/work# AsmetaLc -exit models/asmeta/AISS/lifecycle.asm
parsing file /work/models/asmeta/AISS/lifecycle.asm
file successfully parsed for asm lifecycle
root@7da45b53d672:/work# echo $?
1
```

`AsmetaLc` is just a wrapper around `java -jar AsmetaLc.jar`
