### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by zutshi** [asmeta/asmeta#85]
The links pointing to foselab.unibg.it in the README for downloading eclipse with asmeta are all dead. 
For example: https://foselab.unibg.it/asmeta/eclipse_asmeta_smv_2023_06.zip

**Comment by garganti** [comment]
our server has some problems, we are working on it. Meanwhile, the binaries are available for installing asmeta for a clean eclipse.

**Comment by garganti** [comment]
It is working now - Thanks for letting us know. I will publish a new version of the plugins and zip with eclipse based on 2023_09 in a week.
