### ISSUE TITLE
Lazy evaluation

### ISSUE THREAD

**Issue by a-bombarda** [asmeta/asmeta#94]
The simulator does not seem to use lazy evaluation in the case of `and`s (probably it is the same in the case of `or`s).
For example, in the case of

`if isOn($drawer) and isPillTaken($drawer) then ....`

the value of `isPillTaken($drawer)` is asked to the user even if `isOn($drawer)` is false.

**Comment by garganti** [comment]
now lazy eval shoudl work for BooleanDomain terms. Instead or returning a BooleanValue, the visit returns now a subclass of its, with the getValue method called only when needed

**Comment by garganti** [comment]
I close this issue since it seems to work now
